# setup services 
version: '3'

services:
  dot-djangoserver:
    container_name: dot-djangoserver
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    
    restart: always


  redis:
    image: redis:latest
    container_name: redis-worker


  celery:
    container_name: celery
    build: .
    command: celery -A dotCourses worker -l INFO 
    depends_on:
      - redis
  
  db:
    image: postgres:latest
    container_name: dotCourses_db_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dotCourses
    ports:
      - "5432:5432"

  pgadmin_page:
    image: dpage/pgadmin4
    container_name: pgadmin_page
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin    
    ports:
      - "5050:80"                              
    depends_on:
      - db
volumes:
  postgres_data: