# setup services 
version: '3'

services:
  dot-djangoserver:
    container_name: dot-djangoserver
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app


  redis:
    image: redis:latest
    container_name: redis-worker


  celery:
    container_name: celery
    build: .
    command: celery -A dotCourses worker -l INFO 
    restart: always 
    depends_on:
      - redis
