# Generated by Django 5.0.1 on 2024-03-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default='default.jpeg/', null=True, upload_to=''),
        ),
    ]
