# Generated by Django 5.0.3 on 2024-05-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_certificate_id_certificate_key_grade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('course', 'counter')},
        ),
    ]
