# Generated by Django 5.0.1 on 2024-03-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='d', max_length=120),
            preserve_default=False,
        ),
    ]
