# Generated by Django 5.0.3 on 2024-05-09 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_video_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE core_certificate DROP CONSTRAINT core_certificate_pkey;',
            reverse_sql='ALTER TABLE core_certificate ADD CONSTRAINT core_certificate_pkey PRIMARY KEY (key);',
        ),
        migrations.AddField(
            model_name='certificate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='key',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name="certificate",
            unique_together={("student", "course")},
        ),
        migrations.AlterUniqueTogether(
            name="purchase",
            unique_together={("student", "course")},
        ),
        migrations.AlterUniqueTogether(
            name="rate",
            unique_together={("student", "course")},
        ),
    ]
