# Generated by Django 5.0.3 on 2024-05-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_certificate_id_alter_certificate_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='key',
            field=models.SlugField(),
        ),
    ]
