# Generated by Django 5.0.3 on 2024-05-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_certificate_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_pdf',
            field=models.FileField(null=True, upload_to='certificates/'),
        ),
    ]
