# Generated by Django 5.0.3 on 2024-03-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_course_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default=models.FileField(upload_to='videos/'), max_length=200),
        ),
    ]
