# Generated by Django 5.0.3 on 2024-05-21 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_certificate_certificate_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='right_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer', to='core.choice'),
        ),
    ]
