# Generated by Django 5.0.3 on 2024-03-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_video_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='counter',
            field=models.SmallIntegerField(default=1, verbose_name='number of the video in the course'),
            preserve_default=False,
        ),
    ]
