# Generated by Django 5.0.7 on 2024-11-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_course_discount_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate", 
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
            ),
        migrations.RemoveField(
            model_name="certificate",
            name="id",
        ),
        migrations.AlterField(
            model_name="certificate",
            name="key",
            field=models.SlugField(primary_key=True, serialize=False, unique=True),
        ),
    ]
