# Generated by Django 5.0.3 on 2024-03-20 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_question_right_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RestrictedError, to='core.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='right_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='core.choice'),
        ),
    ]
