# Generated by Django 5.0.7 on 2024-12-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_certificate_id_alter_certificate_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='counter',
            field=models.PositiveSmallIntegerField(verbose_name='number of the video in the course'),
        ),
    ]
