# Generated by Django 5.1.5 on 2025-02-02 21:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_video_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
