# Generated by Django 5.0.3 on 2024-03-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_course_duration_course_rating_course_rating_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.AddField(
            model_name='course',
            name='duration_in_hour',
            field=models.SmallIntegerField(default=0),
        ),
    ]
