# Generated by Django 5.0.3 on 2024-03-25 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_course_duration_course_duration_in_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='student',
        ),
    ]
