# Generated by Django 5.1.5 on 2025-02-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_usercourseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='master_playlist',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
