# Generated by Django 5.0.3 on 2024-03-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_user_cart_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(default='Just Testing', max_length=50),
            preserve_default=False,
        ),
    ]
