# Generated by Django 5.1.5 on 2025-02-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_video_master_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
