# Generated by Django 5.1.5 on 2025-02-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseprogress',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
