# Generated by Django 5.0.3 on 2024-03-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_course_duration_in_hour_course_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='rating_added',
            new_name='rating_added_counter',
        ),
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
        migrations.AddField(
            model_name='course',
            name='rating_sum',
            field=models.IntegerField(default=0),
        ),
    ]
