# Generated by Django 5.0.3 on 2024-03-26 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
