# Generated by Django 5.0.3 on 2024-03-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_test_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.DurationField(),
        ),
    ]
