# Generated by Django 5.0.1 on 2024-04-13 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_course_duration_alter_test_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['counter']},
        ),
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default='default.jpeg/', null=True, upload_to='thumbnail/'),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
