# Generated by Django 5.0.3 on 2024-04-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_question_test_alter_video_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
