# Generated by Django 5.0.3 on 2024-06-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_instructor',
            field=models.BooleanField(default=False),
        ),
    ]
